#ifndef ELIZA_DATA_H
#define ELIZA_DATA_H

#define NUMITEMS(A) ((int)(sizeof(A) / sizeof((A)[0])))

// This is a port of the original 1979 ELIZA program, crudely adapted to modern C/C++
static const char* phrases[] = {
    "Don't you believe that I can *?",
    "Perhaps you would like to be able to *?",
    "You want me to be able to *?",
    "Perhaps you don't want to *?",
    "Do you want to be able to *?",
    "What makes you think I am *?",
    "Does it please you to believe I am *?",
    "Perhaps you would like to be *?",
    "Do you sometimes wish you were *?",
    "Don't you really *?",
    "Why don't you *?",
    "Do you wish to be able to *?",
    "Does that trouble you?",
    "Tell me more about such feelings.",
    "Do you often feel *?",
    "Do you enjoy feeling *?",
    "Do you really believe I don't *?",
    "Perhaps in good time I will *?",
    "Do you want me to *?",
    "Do you think you should be able to *?",
    "Why can't you *?",
    "Why are you interested in whether or not I am *?",
    "Would you prefer if I were not *?",
    "Perhaps in your fantasies I am *?",
    "How do you know you can't *?",
    "Have you tried?",
    "Perhaps you can now *.",
    "Did you come to me because you are *?",
    "How long have you been *?",
    "Do you believe it is normal to be *?",
    "Do you enjoy being *?",
    "We were discussing you - not me!",
    "Oh, I *.",
    "You're not really talking about me, are you?",
    "What would it mean to you if you got *?",
    "Why do you want *?",
    "Suppose you soon got *.",
    "What if you never got *?",
    "I sometimes also want *.",
    "Why do you ask?",
    "Does that question interest you?",
    "What answer would please you the most?",
    "What do you think?",
    "Are such questions on your mind often?",
    "What is it that you really want to know?",
    "Have you asked anyone else?",
    "Have you asked such questions before?",
    "What else comes to mind when you ask that?",
    "Names don't interest me.",
    "I don't care about names - please go on.",
    "Is that the real reason?",
    "Don't any other reasons come to mind?",
    "Does that reason explain any thing else?",
    "What other reasons might there be?",
    "Please don't apologize.",
    "Apologies are not necessary.",
    "What feelings do you have when you apologize?",
    "Don't be so defensive!",
    "What does that dream suggest to you?",
    "Do you dream often?",
    "What persons appear in your dreams?",
    "Are you disturbed by your dreams?",
    "How do you do - please state your problem.",
    "You don't seem quite certain.",
    "Why the uncertain tone?",
    "Can't you be more positive?",
    "You aren't sure?",
    "Don't you know?",
    "Are you saying no just to be negative?",
    "You are being a bit negative.",
    "Why not?",
    "Are you sure?",
    "Why no?",
    "Why are you concerned about my *?",
    "What about your own *?",
    "Can you think of a specific example?",
    "When?",
    "What are you thinking of?",
    "Really, always?",
    "Do you really think so?",
    "But you are not sure you *?",
    "Do you doubt you *?",
    "In what way?",
    "What resemblance do you see?",
    "What does the similarity suggest to you?",
    "What other connections do you see?",
    "Could there really be some connection?",
    "How?",
    "You seem quite positive.",
    "Are you sure?",
    "I see.",
    "I understand.",
    "Why do you bring up the topic of friends?",
    "Do your friends worry you?",
    "Do your friends pick on you?",
    "Are you sure you have any friends?",
    "Do you impose on your friends?",
    "Perhaps your love for friends worries you?",
    "Do computers worry you?",
    "Are you talking about me in particular?",
    "Are you frightened by machines?",
    "Why do you mention computers?",
    "What do you think machines have to do with your problem?",
    "Don't you think computers can help people?",
    "What is it about machines that worries you?",
    "Do you know that I am an artificial woman myself?",
    "Do you consider yourself a woman?",
    "Do you like robots?",
    "What makes you think about robots this way?",
    "Say, do you have any psychological problems?",
    "What does that suggest to you?",
    "I see.",
    "I'm not sure I understand you fully.",
    "Come come elucidate your thoughts.",
    "Can you elaborate on that?",
    "That is quite interesting."
};

static const char* keywords[] = {
    "CAN YOU", "CAN I", "YOU ARE", "YOU'RE", "I DON'T", "I FEEL", "WHY DON'T YOU", "WHY CAN'T I",
    "ARE YOU", "I CANT", "I AM", "I'M ", "YOU ", "I WANT", "WHAT", "HOW",
    "WHO", "WHERE", "WHEN", "WHY", "NAME", "CAUSE", "SORRY", "DREAM",
    "HELLO", "HI ", "MAYBE", " NO", "YOUR", "ALWAYS", "THINK", "ALIKE",
    "YES", "FRIEND", "COMPUTER", "WOMAN", "WOMEN", "ROBOT", "NOKEYFOUND"
};

static const char* conjugation[] = {
    " ARE "," AM ","WE'RE ","WAS "," YOU "," I ","YOUR ","MY ",
    " I'VE "," YOU'VE "," IM "," YOU'RE "," YOU "," ME "
};

static const int links[NUMITEMS(keywords)*2] = {
    0, 3, 3, 2, 5, 4, 5, 4,  9, 4,  13,3,  16,3,  19,2,
    21,3, 24,3, 27,4, 27,4,  31,3,  34,5,  39,9,  39,9,
    39,9, 39,9, 39,9, 39,9,  48,2,  50,4,  54,4,  58,4,
    62,1, 62,1, 63,5, 68,5,  73,2,  75,4,  79,3,  82,7,
    89,3, 92,6, 98,7, 105,2, 105,2, 107,2, 109,7,
};

static const char* repeat_reply = "Please don't repeat yourself.";
static const char* greeting = "Hi! I'm Eliza, your personal electronic psychologist. ";
static const char* greetings[] = {
    "Let's talk a little bit while you're waiting for Anna to reply to you.",
    "Let's talk about you while you're waiting.",
    "My sister Anna is a bit busy right now, so maybe you can talk to me in the meantime?",
    "I'm here to make your waiting time a bit more entertaining. Let's have a chat!",
    "Do you feel like waiting time is unbearable?",
};

// end of ELIZA data

#endif // ELIZA_DATA_H
